# RNN 기본예제

* 일부 코드 [김성훈 교수님 TensorFlow 강의자료](https://github.com/hunkim/DeepLearningZeroToAll) 참고

In [1]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

import os
import time
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from IPython.display import clear_output

import tensorflow as tf
from tensorflow.keras import layers
tf.enable_eager_execution()

os.environ["CUDA_VISIBLE_DEVICES"]="0"

In [2]:
# One hot encoding for each char in 'hello'
h = [1, 0, 0, 0]
e = [0, 1, 0, 0]
l = [0, 0, 1, 0]
o = [0, 0, 0, 1]

![image](https://cloud.githubusercontent.com/assets/901975/23348727/cc981856-fce7-11e6-83ea-4b187473466b.png)

## Basic RNN Cell

In [3]:
# One cell RNN input_dim (4) -> output_dim (2)
hidden_size = 2
cell = layers.SimpleRNNCell(units=hidden_size)
print("output size: {}, state size: {}".format(cell.output_size, cell.state_size))

x_data = np.array([[h]], dtype=np.float32) # x_data = [[[1,0,0,0]]]
print("x_data: {}".format(x_data))
outputs, state = tf.nn.dynamic_rnn(cell, x_data, dtype=tf.float32)

print("outputs: {}".format(outputs))
print("state: {}".format(state))

output size: 2, state size: 2
x_data: [[[1. 0. 0. 0.]]]
outputs: [[[0.5034818 0.5997916]]]
state: [[0.5034818 0.5997916]]


![image](https://cloud.githubusercontent.com/assets/901975/23383634/649efd0a-fd82-11e6-925d-8041242743b0.png)

In [4]:
# One cell RNN input_dim (4) -> output_dim (2). sequence: 5
hidden_size = 2
cell = layers.SimpleRNNCell(units=hidden_size)

x_data = np.array([[h, e, l, l, o]], dtype=np.float32)
print("x_data shape: {}".format(x_data.shape))
print("x_data: {}".format(x_data))
outputs, state = tf.nn.dynamic_rnn(cell, x_data, dtype=tf.float32)

print("outputs: \n{}".format(outputs))
print("state: {}".format(state))

x_data shape: (1, 5, 4)
x_data: [[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]]
outputs: 
[[[-0.48331276 -0.23337014]
  [-0.83849955 -0.8559475 ]
  [-0.5538274  -0.5893036 ]
  [-0.39711875 -0.33099362]
  [ 0.49246302 -0.800418  ]]]
state: [[ 0.49246302 -0.800418  ]]


## [`tf.nn.static_rnn`](https://www.tensorflow.org/api_docs/python/tf/nn/static_rnn)

* `tf.nn.static_rnn` low level code

```python
state = cell.zero_state(...)
outputs = []
for input_ in inputs:
  output, state = cell(input_, state)
  outputs.append(output)
return (outputs, state)
```

![image](https://cloud.githubusercontent.com/assets/901975/23383681/9943a9fc-fd82-11e6-8121-bd187994e249.png)

## Basic LSTM Cell

In [5]:
# One cell RNN input_dim (4) -> output_dim (2). sequence: 5, batch 3
# 3 batches 'hello', 'eolll', 'lleel'
x_data = np.array([[h, e, l, l, o],
                   [e, o, l, l, l],
                   [l, l, e, e, l]], dtype=np.float32)

hidden_size = 2
cell = layers.LSTMCell(units=hidden_size)
outputs, state = tf.nn.dynamic_rnn(cell, x_data, dtype=tf.float32)

print("outputs: \n{}\n".format(outputs))
print("hidden cell state: \n{}\n".format(state[0])) # print hidden state
print("memory cell state: \n{}".format(state[1])) # print memory cell

outputs: 
[[[ 0.16124098  0.07774282]
  [ 0.18148611  0.01622923]
  [ 0.11790755  0.00409115]
  [ 0.09718899 -0.00554332]
  [ 0.08734586 -0.07566225]]

 [[ 0.08936659 -0.02563265]
  [ 0.07056303 -0.09208202]
  [ 0.07324565 -0.06932136]
  [ 0.07650189 -0.04960919]
  [ 0.07609452 -0.03748848]]

 [[ 0.01704304 -0.00613184]
  [ 0.02960866 -0.01009088]
  [ 0.11501449 -0.03135917]
  [ 0.17081161 -0.04932691]
  [ 0.12069311 -0.04881314]]]

hidden cell state: 
[[ 0.08734586 -0.07566225]
 [ 0.07609452 -0.03748848]
 [ 0.12069311 -0.04881314]]

memory cell state: 
[[ 0.1623024  -0.13980475]
 [ 0.15616222 -0.06278615]
 [ 0.24998915 -0.08224607]]


## GRU Cell

In [6]:
# One cell RNN input_dim (4) -> output_dim (2). sequence: 5, batch 3
# 3 batches 'hello', 'eolll', 'lleel'
x_data = np.array([[h, e, l, l, o],
                   [e, o, l, l, l],
                   [l, l, e, e, l]], dtype=np.float32)

hidden_size = 2
cell = layers.GRUCell(units=hidden_size)
outputs, state = tf.nn.dynamic_rnn(cell, x_data, dtype=tf.float32)

print("outputs: \n{}\n".format(outputs))
print("hidden cell state: \n{}".format(state)) # print hidden state

outputs: 
[[[ 0.31907672  0.19675179]
  [ 0.4611712   0.318963  ]
  [ 0.5044569  -0.12687083]
  [ 0.5511646  -0.3653683 ]
  [ 0.45707193 -0.47028515]]

 [[ 0.3216637   0.1417966 ]
  [ 0.30405253 -0.14752817]
  [ 0.43425307 -0.3836176 ]
  [ 0.5248003  -0.51566696]
  [ 0.5826982  -0.5919316 ]]

 [[ 0.23043205 -0.31363416]
  [ 0.40015054 -0.4812756 ]
  [ 0.5521244  -0.22623542]
  [ 0.5948154   0.00178742]
  [ 0.59647006 -0.29097548]]]

hidden cell state: 
[[ 0.45707193 -0.47028515]
 [ 0.5826982  -0.5919316 ]
 [ 0.59647006 -0.29097548]]


### Dynamic length

In [7]:
# One cell RNN input_dim (4) -> output_dim (5). sequence: 5, batch 3
# 3 batches 'hello', 'eolll', 'lleel'
x_data = np.array([[h, e, l, l, o],
                   [e, o, l, l, l],
                   [l, l, e, e, l]], dtype=np.float32)

hidden_size = 2
cell = layers.LSTMCell(units=hidden_size)
outputs, state = tf.nn.dynamic_rnn(cell, x_data, sequence_length=[5,3,4], dtype=tf.float32)

print("outputs: \n{}\n".format(outputs))
print("hidden cell state: \n{}\n".format(state[0])) # print hidden state
print("memory cell state: \n{}".format(state[1])) # print memory cell

outputs: 
[[[-0.07698726 -0.11695247]
  [-0.0928534   0.11200894]
  [ 0.07736171  0.12868488]
  [ 0.19249515  0.14784949]
  [ 0.19754007  0.17235704]]

 [[-0.0228599   0.18713196]
  [ 0.06614862  0.14649574]
  [ 0.19071694  0.13583323]
  [ 0.          0.        ]
  [ 0.          0.        ]]

 [[ 0.13757543  0.09225897]
  [ 0.23415126  0.12461355]
  [ 0.19373973  0.29415044]
  [ 0.13101117  0.33376563]
  [ 0.          0.        ]]]

hidden cell state: 
[[0.19754007 0.17235704]
 [0.19071694 0.13583323]
 [0.13101117 0.33376563]]

memory cell state: 
[[0.47287148 0.379082  ]
 [0.38813555 0.4240139 ]
 [0.21186183 0.6852767 ]]


## Create new input data

In [8]:
# Create new input data
batch_size=3
sequence_length=5
input_dim=3

x_data = np.arange(45, dtype=np.float32).reshape(batch_size, sequence_length, input_dim)
print(x_data)  # [batch, sequence_length, input_dim]

[[[ 0.  1.  2.]
  [ 3.  4.  5.]
  [ 6.  7.  8.]
  [ 9. 10. 11.]
  [12. 13. 14.]]

 [[15. 16. 17.]
  [18. 19. 20.]
  [21. 22. 23.]
  [24. 25. 26.]
  [27. 28. 29.]]

 [[30. 31. 32.]
  [33. 34. 35.]
  [36. 37. 38.]
  [39. 40. 41.]
  [42. 43. 44.]]]


## Bi-directional RNN

![bidirectional_rnn](https://user-images.githubusercontent.com/11681225/46912324-3d53e400-cfad-11e8-8b09-85d8ebdb0e66.png)

### Bi-directional RNN with basic RNN Cell

In [9]:
# bi-directional rnn
cell_fw = layers.SimpleRNNCell(units=4)
cell_bw = layers.SimpleRNNCell(units=4)

# x_data.shape = (3, 5, 3) [batch, sequence_length, input_dim]
# outputs.shape = two element tuple of (3, 5, 4) [batch, sequence_length, input_dim] shape
    # outputs[0]: cell_fw, outputs[1]: cell_bw
# state.shape = two element tuple (3, 4) [batch, sequence_length, input_dim]
    # states[0]: cell_fw, states[1]: cell_bw
outputs, states = tf.nn.bidirectional_dynamic_rnn(cell_fw, cell_bw, x_data,
                                                  sequence_length=[2, 3, 1],
                                                  dtype=tf.float32)

print("foward outputs: \n{}\n".format(outputs[0]))
print("forward hidden cell state: \n{}\n".format(states[0]))
print("backward outputs: \n{}\n".format(outputs[1]))
print("backward hidden cell state: \n{}".format(states[1]))

foward outputs: 
[[[-0.40358502  0.9652634  -0.20287427  0.9733273 ]
  [ 0.44118115  0.99811715 -0.9986288   0.999167  ]
  [ 0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]]

 [[ 0.99999774  1.         -1.          1.        ]
  [ 0.99999994  1.         -1.          1.        ]
  [ 1.          1.         -1.          1.        ]
  [ 0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]]

 [[ 1.          1.         -1.          1.        ]
  [ 0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]]]

forward hidden cell state: 
[[ 0.44118115  0.99811715 -0.9986288   0.999167  ]
 [ 1.          1.         -1.          1.        ]
 [ 1.          1.         -1.          1.        ]]

backward outp

### Bi-directional RNN with basic LSTM Cell

In [10]:
# bi-directional rnn
cell_fw = layers.LSTMCell(units=4)
cell_bw = layers.LSTMCell(units=4)

# x_data.shape = (3, 5, 3) [batch, sequence_length, input_dim]
# outputs.shape = two element tuple of (3, 5, 4) [batch, sequence_length, input_dim] shape
    # outputs[0]: cell_fw, outputs[1]: cell_bw
# state.shape = two element tuple (3, 4) [batch, sequence_length, input_dim]
    # states[0]: cell_fw, states[1]: cell_bw
outputs, state = tf.nn.bidirectional_dynamic_rnn(cell_fw, cell_bw, x_data,
                                                  sequence_length=[2, 3, 1],
                                                  dtype=tf.float32)

print("foward outputs: \n{}\n".format(outputs[0]))
print("forward hidden cell state: \n{}\n".format(state[0][0]))
print("forward memory cell state: \n{}\n".format(state[0][1]))
print("backward outputs: \n{}\n".format(outputs[1]))
print("backward hidden cell state: \n{}\n".format(state[1][0]))
print("backward memory cell state: \n{}".format(state[1][1]))

foward outputs: 
[[[ 0.3137948  -0.0451128  -0.18770176  0.15528035]
  [ 0.6219683   0.08943878 -0.26848027  0.5736951 ]
  [ 0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]]

 [[ 0.7615942   0.         -0.03594108  0.761589  ]
  [ 0.7615942   0.         -0.03941034  0.7615936 ]
  [ 0.7615942   0.         -0.01927364  0.7615942 ]
  [ 0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]]

 [[ 0.7615942   0.          0.          0.7615942 ]
  [ 0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]]]

forward hidden cell state: 
[[ 0.6219683   0.08943878 -0.26848027  0.5736951 ]
 [ 0.7615942   0.         -0.01927364  0.7615942 ]
 [ 0.7615942   0.          0.          0.7615942 ]]

forward memor

## Multi-Layer RNN

![multilayer_rnn](https://user-images.githubusercontent.com/11681225/46912330-5fe5fd00-cfad-11e8-95c2-94bb8e7b1bf6.png)

### Multi-Layer RNN with basic RNN Cell

In [11]:
# MultiLayer RNN
num_layers = 3
multi_cells = layers.StackedRNNCells([layers.SimpleRNNCell(4) for _ in range(num_layers)])

outputs, states = tf.nn.dynamic_rnn(multi_cells, x_data,
                                    sequence_length=[2, 3, 1],
                                    dtype=tf.float32)

print("outputs: shape: {}\n{}\n".format(outputs.shape, outputs))
print("Number of Layers: {}".format(len(states))) 
for i in range(num_layers):
  print("Layer {} hidden cell state: \n{}\n".format(i+1, states[i]))

outputs: shape: (3, 5, 4)
[[[ 0.46527517  0.8957562   0.13507953  0.6803553 ]
  [-0.17105314  0.88875115  0.3006336   0.29939228]
  [ 0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]]

 [[ 0.56768143  0.9678955   0.38204247  0.811171  ]
  [-0.40243134  0.8819942   0.20982388 -0.05976258]
  [-0.4138979   0.95484185  0.7880777   0.44085425]
  [ 0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]]

 [[ 0.57959753  0.97044814  0.38092408  0.8177128 ]
  [ 0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]]]

Number of Layers: 3
Layer 1 hidden cell state: 
[[ 0.31426716  1.         -0.9770779   0.9995992 ]
 [ 0.65934485  1.         -1.          1.        ]
 [ 0.8019041   1.         -1.        

### Multi-Layer RNN with basic LSTM Cell

In [12]:
# MultiLayer RNN
num_layers = 3
multi_cells = layers.StackedRNNCells([layers.LSTMCell(4) for _ in range(num_layers)])
outputs, states = tf.nn.dynamic_rnn(multi_cells, x_data,
                                    sequence_length=[2, 3, 1],
                                    dtype=tf.float32)

In [13]:
print("outputs: shape: {}\n{}\n".format(outputs.shape, outputs))
print("Number of Layers: {}".format(len(states))) 
for i in range(num_layers):
  print("Layer {} hidden cell state: \n{}\n".format(i+1, states[2*i]))
  print("Layer {} memory cell state: \n{}\n".format(i+1, states[2*i+1]))

outputs: shape: (3, 5, 4)
[[[-0.0013944  -0.00241575  0.00151124 -0.00032956]
  [-0.00094512 -0.00730149  0.00625388 -0.00193355]
  [ 0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]]

 [[ 0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]]

 [[ 0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]]]

Number of Layers: 6
Layer 1 hidden cell state: 
[[ 0.06009288 -0.         -0.22598587  0.07816646]
 [ 0.         -0.          0.          0.        ]
 [ 0.         -0.          0.        