# TensorFlow Eager Execution

In [1]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import tensorflow as tf
import tensorflow.contrib.eager as tfe

tf.enable_eager_execution()

print("TensorFlow version: {}".format(tf.VERSION))
print("Eager execution: {}".format(tf.executing_eagerly()))

TensorFlow version: 1.11.0
Eager execution: True


## Execution Style

* [Eager execution](https://www.tensorflow.org/get_started/eager)
  * 최근에 나온 방식
  * 변수값을 바로 확인할 수 있음
  * 마치 `numpy` 짜듯이 짤 수 있음
* [Graph execution](https://www.tensorflow.org/get_started/get_started_for_beginners)
  * TensorFlow 초창기 구현 방법
  * 여전히 많이 이용하고 있음
  * Graph 선언부분과 실행(Session)하는 부분이 분리되어 있음

## Eager Execution examples

In [2]:
a = tf.add(3, 5)

In [3]:
print(a)

tf.Tensor(8, shape=(), dtype=int32)


### 약간 더 복잡한 계산

In [4]:
x = 2
y = 3
w = tf.add(x, y)
z = tf.multiply(x, y)
p = tf.pow(z, w)
print("x: ", x)
print("y: ", y)
print("w: ", w)
print("z: ", z)
print("p: ", p)

x:  2
y:  3
w:  tf.Tensor(5, shape=(), dtype=int32)
z:  tf.Tensor(6, shape=(), dtype=int32)
p:  tf.Tensor(7776, shape=(), dtype=int32)


### `Tensor` 변수와 일반 `python` 변수

In [5]:
x = tf.constant(2)
y = tf.constant(3)
w = x + y
z = x * y
p = tf.pow(z, w)
print("x: ", x)
print("y: ", y)
print("w: ", w)
print("z: ", z)
print("p: ", p)

x:  tf.Tensor(2, shape=(), dtype=int32)
y:  tf.Tensor(3, shape=(), dtype=int32)
w:  tf.Tensor(5, shape=(), dtype=int32)
z:  tf.Tensor(6, shape=(), dtype=int32)
p:  tf.Tensor(7776, shape=(), dtype=int32)


### Eager Execution another examples

In [6]:
tf.executing_eagerly()        # => True

x = [[2.]]
m = tf.matmul(x, x)
print("hello, {}".format(m))  # => "hello, [[4.]]"

hello, [[4.]]


In [7]:
a = tf.constant([[1, 2],
                 [3, 4]])
print(a)
# => tf.Tensor([[1 2]
#               [3 4]], shape=(2, 2), dtype=int32)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [8]:
# Broadcasting support
b = tf.add(a, 1)
print(b)
# => tf.Tensor([[2 3]
#               [4 5]], shape=(2, 2), dtype=int32)

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)


In [9]:
# Operator overloading is supported
print(a * b)
# => tf.Tensor([[ 2  6]
#               [12 20]], shape=(2, 2), dtype=int32)

tf.Tensor(
[[ 2  6]
 [12 20]], shape=(2, 2), dtype=int32)


In [10]:
# Use NumPy functions
import numpy as np

c = np.multiply(a, b)
print(c)
# => [[ 2  6]
#     [12 20]]

[[ 2  6]
 [12 20]]


### `tf.Tensor.numpy()`

* returns the object's value as a NumPy ndarray.

In [11]:
# Obtain numpy value from a tensor:
print(a.numpy())
# => [[1 2]
#     [3 4]]

[[1 2]
 [3 4]]
