# TensorFlow Dimension

In [1]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import tensorflow as tf

sess_config = tf.ConfigProto(gpu_options=tf.GPUOptions(allow_growth=True))

## What is Tensor?

* Tensor: An n-dimensional array (rough하게)
  * rank 0: scalar
  * rank 1: vector
  * rank 2: matrix
  * rank 3: 3-tensor (cube 모양)
  * rank n: n-tensor

### Dimension과 자주 쓰이는 Constant Value Tensors API를 함께 알아보자

* [Constant Value Tensors](https://www.tensorflow.org/api_guides/python/constant_op#Constant_Value_Tensors)
  * `tf.constant`
  * `tf.zeros`
  * `tf.zeros_like`
  * `tf.ones`
  * `tf.ones_like`
  * `tf.fill`
* Sequences Tensors
  * `tf.linspace`
  * `tf.range`

In [2]:
# rank 0 tensor: scalar
a = tf.constant(3, name='a')
print(a)

Tensor("a:0", shape=(), dtype=int32)


In [3]:
# rank 1 tensor: vector
b = tf.zeros([2])
print(b)

Tensor("zeros:0", shape=(2,), dtype=float32)


In [4]:
# rank 2 tensor: matrix
c = tf.ones([2, 3])
print(c)

Tensor("ones:0", shape=(2, 3), dtype=float32)


In [5]:
# rank 3 tensor: 3-tensor
d = tf.fill([2, 3, 4], 3)
print(d)

Tensor("Fill:0", shape=(2, 3, 4), dtype=int32)


In [6]:
# ones_like
e = tf.ones_like(d)
print(e)

Tensor("ones_like:0", shape=(2, 3, 4), dtype=int32)


In [7]:
# linespace
f = tf.linspace(1.0, 5.0, 4)
print(f)

Tensor("LinSpace:0", shape=(4,), dtype=float32)


In [8]:
print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)
print(e.shape)
print(f.shape)

()
(2,)
(2, 3)
(2, 3, 4)
(2, 3, 4)
(4,)


In [9]:
print(a.name)
print(b.name)
print(c.name)
print(d.name)
print(e.name)
print(f.name)

a:0
zeros:0
ones:0
Fill:0
ones_like:0
LinSpace:0


### `tf.Session()`을 사용하여 값을 출력해보자

In [10]:
with tf.Session(config=sess_config) as sess:
  print('a:', sess.run(a), '\n')
  print('b:', sess.run(b), '\n')
  print('c:', sess.run(c), '\n')
  print('d:', sess.run(d), '\n')
  print('e:', sess.run(e), '\n')
  print('f:', sess.run(f))

a: 3 

b: [0. 0.] 

c: [[1. 1. 1.]
 [1. 1. 1.]] 

d: [[[3 3 3 3]
  [3 3 3 3]
  [3 3 3 3]]

 [[3 3 3 3]
  [3 3 3 3]
  [3 3 3 3]]] 

e: [[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]] 

f: [1.        2.3333335 3.6666667 5.       ]


### 여러 변수들 session을 이용하여 한번에 실행

In [11]:
with tf.Session(config=sess_config) as sess:
  u, v, w, x, y, z = sess.run([a, b, c, d, e, f])
  #print(u, v, w, x, y, z)
  print('a:', u, '\n')
  print('b:', v, '\n')
  print('c:', w, '\n')
  print('d:', x, '\n')
  print('e:', y, '\n')
  print('f:', z)

a: 3 

b: [0. 0.] 

c: [[1. 1. 1.]
 [1. 1. 1.]] 

d: [[[3 3 3 3]
  [3 3 3 3]
  [3 3 3 3]]

 [[3 3 3 3]
  [3 3 3 3]
  [3 3 3 3]]] 

e: [[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]] 

f: [1.        2.3333335 3.6666667 5.       ]


### 자주 쓰는 Random Tensors 들도 사용해보자

* [Random Tensors](https://www.tensorflow.org/api_guides/python/constant_op#Random_Tensors)
  * `tf.random_normal`
  * `tf.truncated_normal`
  * `tf.random_uniform`
  * `tf.random_shuffle`
  * `tf.random_crop`
  * `tf.multinomial`
  * `tf.random_gamma`
  * `tf.set_random_seed`

### set random number seed

In [12]:
tf.set_random_seed(219)

In [13]:
g = tf.random_normal([2, 3])
h = tf.random_uniform([2, 3, 4])

In [14]:
print(g)
print(h)

Tensor("random_normal:0", shape=(2, 3), dtype=float32)
Tensor("random_uniform:0", shape=(2, 3, 4), dtype=float32)


In [15]:
print(g.shape)
print(h.shape)

(2, 3)
(2, 3, 4)


In [16]:
print(g.name)
print(h.name)

random_normal:0
random_uniform:0


### `tf.Session()`을 사용하여 값을 출력해보자

In [17]:
with tf.Session(config=sess_config) as sess:
  p, q = sess.run([g, h])
  print('g:')
  print(p, '\n')
  print('f:')
  print(q, '\n')

g:
[[-0.40596983 -0.7377229   0.14824887]
 [-0.34252906  0.01030455  0.23464671]] 

f:
[[[0.40151834 0.823539   0.10896671 0.0895896 ]
  [0.76094246 0.6268629  0.3829553  0.14131594]
  [0.37183535 0.18341827 0.7777599  0.56934345]]

 [[0.07371569 0.57423997 0.80455744 0.08843875]
  [0.44586277 0.3187152  0.95220935 0.22553825]
  [0.8526783  0.3939433  0.8976431  0.04104459]]] 



## 직접 실습

### 2D Tensor (matrix) 더하기 및 곱하기

* 2 x 2 random matrix 생성
  * x = [ [1, 2], [3, 4] ]
  * y = [ [5, 6], [7, 8] ]
* elementwise 더하기
* elementwise 곱하기
* matrix 곱하기

In [18]:
# TODO
x = tf.convert_to_tensor([ [1, 2], [3, 4] ])
y = tf.convert_to_tensor([ [5, 6], [7, 8] ])
# z: elementwise 더하기
z = x + y
# w: elementwise 곱하기
w = x * y
# v: matrix 곱하기
v = tf.matmul(x, y)

with tf.Session(config=sess_config) as sess:
  print(sess.run(x))
  print(sess.run(y))
  print(sess.run(z))
  print(sess.run(w))
  print(sess.run(v))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


##### output
```python
[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
```

### 3D Tensor 단면 자르기
* tf.range를 이용하여 3 x 2 x 2 = 12 element list 생성
* tf.reshape을 통해 3D Tensor 변환

In [19]:
# TODO
x = tf.range(12)
x = tf.reshape(x, [3, 2, 2])

# index를 이용하여 slice
y = x[0,:,:] + x[2,:,:]

with tf.Session(config=sess_config) as sess:
  print('x:')
  print(sess.run(x), '\n')
  print('x\'s first channel:')
  print(sess.run(x[0,:,:]), '\n')
  print('x\'s last channel:')
  print(sess.run(x[2,:,:]), '\n')
  print('y:')
  print(sess.run(y))

x:
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]] 

x's first channel:
[[0 1]
 [2 3]] 

x's last channel:
[[ 8  9]
 [10 11]] 

y:
[[ 8 10]
 [12 14]]


##### output
```python
x:
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]] 

x's first channel:
[[0 1]
 [2 3]] 

x's last channel:
[[ 8  9]
 [10 11]] 

y:
[[ 8 10]
 [12 14]]
```